### ISSUE TITLE
签到失败：请使用 post 方法

### ISSUE THREAD

**Issue by q7q7q7q7q7q7q7** [AKA-Cigma/qinglong-backup#1]
---------登录阿里云盘------------
10:01:40.289 aligo.INFO Config /root/.aligo/aligo.json
10:01:40.289 aligo.INFO 日志等级 INFO
10:01:40.289 aligo.INFO aligo 版本 6.1.8
10:01:40.289 aligo.INFO 类 Unix 操作系统
10:01:40.289 aligo.INFO 加载配置文件 /root/.aligo/aligo.json
10:01:40.290 aligo.INFO ---------2023-10-23 10:01:40 签到程序开始执行------------
10:01:40.290 aligo.INFO ！！！签到失败：请使用 post 方法！！！

**Comment by AKA-Cigma** [comment]
修改readme指定安装版本aligo==6.0.4
