### ISSUE TITLE
EXEC_SIGN_IN变量问题

### ISSUE THREAD

**Issue by xigua0123** [AKA-Cigma/qinglong-backup#3]
EXEC_SIGN_IN变量问无论填写true、false、False 、True都会报错

 EXEC_SIGN_IN = int(env("EXEC_SIGN_IN"))
                   ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'False'

**Comment by xigua0123** [comment]
只能手动将EXEC_SIGN_IN = True  # 默认开启签到
改成EXEC_SIGN_IN = False才可以不签到，但是一拉库就会覆盖

**Comment by AKA-Cigma** [comment]
已修复
