### ISSUE TITLE
 QLBK_EXCLUDE_NAMES 变量

### ISSUE THREAD

**Issue by xigua0123** [AKA-Cigma/qinglong-backup#4]
export QLBK_EXCLUDE_NAMES="['log', '.git', '.github', 'node_modules', 'backups', '.pnpm-store', 'repo', 'syslog']"这样写会报错
变量 QLBK_EXCLUDE_NAMES 格式错误: Expecting value: line 1 column 2 (char 1)，已自动重设为默认值
但是原来的是不报错的，
如果将脚本内的  QLBK_EXCLUDE_NAMES = ['log', '.git', '.github', 'node_modules', 'backups', '.pnpm-store']  # 排除目录名
改成   QLBK_EXCLUDE_NAMES = ['log', '.git', '.github', 'node_modules', 'backups', '.pnpm-store', 'repo', 'syslog'] 
就正常，不报错

**Comment by xigua0123** [comment]
QLBK_EXCLUDE_NAMES = ['log', '.git', '.github',
                      'node_modules', 'backups', '.pnpm-store']  # 排除目录名
if env("QLBK_EXCLUDE_NAMES"):
    try:
        QLBK_EXCLUDE_NAMES = json.loads(str(env("QLBK_EXCLUDE_NAMES")))
        logger.warning(f'检测到设置变量 QLBK_EXCLUDE_NAMES = {QLBK_EXCLUDE_NAMES}')
    except Exception as e:
        logger.error(f'变量 QLBK_EXCLUDE_NAMES 格式错误: {str(e)}，已自动重设为默认值')

改回去

QLBK_EXCLUDE_NAMES = ['log', '.git', '.github',
                      'node_modules', 'backups', '.pnpm-store']  # 排除目录名
if env("QLBK_EXCLUDE_NAMES"):
    QLBK_EXCLUDE_NAMES = env("QLBK_EXCLUDE_NAMES")
    logger.info(f'检测到设置变量 QLBK_EXCLUDE_NAMES = {QLBK_EXCLUDE_NAMES}')

就正常了

**Comment by AKA-Cigma** [comment]
已修复，被之前的README误导了
